name: Publish

on:
  push:
    branches:
      - main
      - beta
      - alpha

permissions:
  contents: write      # semantic-release doit écrire des tags & changelog
  issues: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # IMPORTANT pour semantic-release

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Update version
        run: bun run scripts/update-version.ts

      - name: Get new version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Tag
        run: |
          git add package.json
          git commit -m "chore(release): ${{ steps.get_version.outputs.VERSION }} [skip ci]"
          git tag v${{ steps.get_version.outputs.VERSION }}
          git push origin HEAD --tags

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
